"""update group table

Revision ID: 0203bb356b27
Revises: 9e5f4003d35d
Create Date: 2024-12-07 01:59:14.708870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0203bb356b27'
down_revision: Union[str, None] = '9e5f4003d35d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('groups', 'instructor_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('groups', 'instructor_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
