"""add changes with columns

Revision ID: e4ece9b933e4
Revises: 71288154189e
Create Date: 2024-12-01 17:22:15.646662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4ece9b933e4'
down_revision: Union[str, None] = '71288154189e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('studentsubjects', sa.Column('rate_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'studentsubjects', 'rates', ['rate_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'studentsubjects', type_='foreignkey')
    op.drop_column('studentsubjects', 'rate_id')
    op.drop_table('rates')
    # ### end Alembic commands ###
